name = "aka-d3rpp-dev"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-07"

kv_namespaces = [
	{ binding = "URLS", id = "2f3fec562af142a3aab551a6dc529766", preview_id = "98bc2b6612ee4ec29fff0c99ce310e08" }
]

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"