name = "aka-d3rpp-dev"
main ="src/index.ts"
compatibility_date = "2023-03-07"

kv_namespaces = [
	{ binding = "URLS", id = "2f3fec562af142a3aab551a6dc529766", preview_id = "98bc2b6612ee4ec29fff0c99ce310e08" }
]
